name: CTA
state: {}
props: []
ui:
  tag: div
  class: bg-white
  children:
    - tag: div
      class: mx-auto max-w-7xl py-24 sm:px-6 sm:py-32 lg:px-8
      children:
        - tag: div
          class: >-
            relative isolate overflow-hidden bg-gray-900 px-6 pt-16 shadow-2xl
            sm:rounded-3xl sm:px-16 md:pt-24 lg:flex lg:gap-x-20 lg:px-24
            lg:pt-0
          children:
            - tag: svg
              xmlns: http://www.w3.org/2000/svg
              viewBox: 0 0 1024 1024
              aria-hidden: 'true'
              class: >-
                absolute top-1/2 left-1/2 -z-10 h-[64rem] w-[64rem]
                -translate-y-1/2
                [mask-image:radial-gradient(closest-side,white,transparent)]
                sm:left-full sm:-ml-80 lg:left-1/2 lg:ml-0 lg:translate-y-0
                lg:-translate-x-1/2
              children:
                - tag: circle
                  cx: '{512}'
                  cy: '{512}'
                  r: '{512}'
                  fill: url(#759c1415-0410-454c-8f7c-9a820de03641)
                  fillOpacity: '0.7'
                - tag: defs
                  children:
                    - tag: radialGradient
                      id: 759c1415-0410-454c-8f7c-9a820de03641
                      children:
                        - tag: stop
                          stopColor: '#7775D6'
                        - tag: stop
                          offset: '{1}'
                          stopColor: '#E935C1'
            - tag: div
              class: >-
                mx-auto max-w-md text-center lg:mx-0 lg:flex-auto lg:py-32
                lg:text-left
              children:
                - tag: h2
                  class: text-3xl font-foundation tracking-tight text-white sm:text-4xl
                  children:
                    - Boost your productivity.
                    - tag: br
                    - Start using our app today.
                - tag: p
                  class: mt-6 text-lg leading-8 text-gray-300
                  children:
                    - >-
                      Ac euismod vel sit maecenas id pellentesque eu sed
                      consectetur. Malesuada adipiscing sagittis vel nulla.
                - tag: div
                  class: >-
                    mt-10 flex items-center justify-center gap-x-6
                    lg:justify-start
                  children:
                    - tag: a
                      href: '#'
                      class: >-
                        rounded-md bg-white px-3.5 py-1.5 text-base
                        font-semibold leading-7 text-gray-900 shadow-sm
                        hover:bg-gray-100 focus-visible:outline
                        focus-visible:outline-2 focus-visible:outline-offset-2
                        focus-visible:outline-white
                      children:
                        - Get started
                    - tag: a
                      href: '#'
                      class: text-base font-semibold leading-7 text-white
                      children:
                        - Learn more
                        - tag: span
                          aria-hidden: 'true'
                          children:
                            - â†’
            - tag: div
              class: relative mt-16 h-80 lg:mt-8
              children:
                - tag: img
                  src: >-
                    https://tailwindui.com/img/component-images/dark-project-app-screenshot.png
                  alt: App screenshot
                  width: '{1824}'
                  height: '{1080}'
                  class: >-
                    absolute top-0 left-0 w-[57rem] max-w-none rounded-md
                    bg-white/5 ring-1 ring-white/10
